import type { DesignTokens } from '../tokens';

export const corporatePreset: DesignTokens = {
  id: 'corporate',
  name: 'Corporate',
  mode: 'light',
  colors: {
    primary: '#1d4ed8',
    primaryLight: '#3b82f6',
    primaryDark: '#1e40af',
    secondary: '#0f172a',
    accent: '#0ea5e9',
    background: '#ffffff',
    surface: '#f8fafc',
    surfaceHover: '#f1f5f9',
    text: '#0f172a',
    textMuted: '#475569',
    textSubtle: '#94a3b8',
    border: '#e2e8f0',
    borderHover: '#cbd5e1',
    gradient: { from: '#1d4ed8', to: '#0ea5e9', angle: 135 },
  },
  typography: {
    headingFont: "'Plus Jakarta Sans', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: 700,
    bodyWeight: 400,
    h1: '3.5rem',
    h2: '2.5rem',
    h3: '1.5rem',
    h4: '1.25rem',
    body: '1rem',
    small: '0.875rem',
    lineHeight: 1.65,
    headingLineHeight: 1.2,
    letterSpacing: '0em',
    headingLetterSpacing: '-0.02em',
  },
  spacing: {
    sectionY: '5.5rem',
    sectionX: '1.5rem',
    containerMax: '1200px',
    gap: '1.5rem',
    gapLg: '2.5rem',
    cardPadding: '1.75rem',
    cardPaddingLg: '2.5rem',
  },
  shapes: {
    radius: '8px',
    radiusSm: '4px',
    radiusLg: '12px',
    radiusXl: '16px',
    radiusFull: '9999px',
    cardRadius: '12px',
    buttonRadius: '8px',
    imageRadius: '12px',
    inputRadius: '8px',
  },
  effects: {
    shadow: '0 1px 3px rgba(0,0,0,0.08)',
    shadowLg: '0 8px 24px rgba(0,0,0,0.1)',
    cardShadow: '0 2px 8px rgba(0,0,0,0.06)',
    buttonShadow: '0 2px 8px rgba(29,78,216,0.25)',
    glowColor: '#1d4ed8',
    glowOpacity: 0.08,
    glassmorphism: false,
    gradientOverlay: false,
    noise: false,
    gridPattern: false,
    animationSpeed: 'normal',
  },
  buttons: {
    primary: {
      bg: '#1d4ed8',
      text: '#ffffff',
      hoverBg: '#1e40af',
      shadow: '0 2px 8px rgba(29,78,216,0.3)',
      padding: '0.75rem 2rem',
      fontSize: '0.875rem',
      fontWeight: 600,
    },
    secondary: {
      bg: '#ffffff',
      text: '#1d4ed8',
      border: '1px solid #e2e8f0',
      hoverBg: '#f8fafc',
      padding: '0.75rem 2rem',
      fontSize: '0.875rem',
      fontWeight: 500,
    },
  },
};
