import type { DesignTokens } from '../tokens';

export const minimalPreset: DesignTokens = {
  id: 'minimal',
  name: 'Minimal',
  mode: 'light',
  colors: {
    primary: '#18181b',
    primaryLight: '#3f3f46',
    primaryDark: '#09090b',
    secondary: '#71717a',
    accent: '#18181b',
    background: '#ffffff',
    surface: '#fafafa',
    surfaceHover: '#f4f4f5',
    text: '#18181b',
    textMuted: '#52525b',
    textSubtle: '#a1a1aa',
    border: '#e4e4e7',
    borderHover: '#d4d4d8',
    gradient: { from: '#18181b', to: '#3f3f46', angle: 180 },
  },
  typography: {
    headingFont: "'DM Sans', sans-serif",
    bodyFont: "'DM Sans', sans-serif",
    headingWeight: 600,
    bodyWeight: 400,
    h1: '3.25rem',
    h2: '2.25rem',
    h3: '1.5rem',
    h4: '1.125rem',
    body: '1rem',
    small: '0.875rem',
    lineHeight: 1.7,
    headingLineHeight: 1.2,
    letterSpacing: '0em',
    headingLetterSpacing: '-0.02em',
  },
  spacing: {
    sectionY: '5rem',
    sectionX: '1.5rem',
    containerMax: '1100px',
    gap: '1.25rem',
    gapLg: '2.5rem',
    cardPadding: '1.5rem',
    cardPaddingLg: '2.5rem',
  },
  shapes: {
    radius: '6px',
    radiusSm: '4px',
    radiusLg: '8px',
    radiusXl: '12px',
    radiusFull: '9999px',
    cardRadius: '8px',
    buttonRadius: '6px',
    imageRadius: '8px',
    inputRadius: '6px',
  },
  effects: {
    shadow: '0 1px 2px rgba(0,0,0,0.05)',
    shadowLg: '0 4px 12px rgba(0,0,0,0.08)',
    cardShadow: '0 1px 3px rgba(0,0,0,0.06)',
    buttonShadow: 'none',
    glowColor: 'transparent',
    glowOpacity: 0,
    glassmorphism: false,
    gradientOverlay: false,
    noise: false,
    gridPattern: false,
    animationSpeed: 'none',
  },
  buttons: {
    primary: {
      bg: '#18181b',
      text: '#ffffff',
      hoverBg: '#3f3f46',
      shadow: 'none',
      padding: '0.75rem 1.75rem',
      fontSize: '0.875rem',
      fontWeight: 500,
    },
    secondary: {
      bg: 'transparent',
      text: '#18181b',
      border: '1px solid #e4e4e7',
      hoverBg: '#fafafa',
      padding: '0.75rem 1.75rem',
      fontSize: '0.875rem',
      fontWeight: 500,
    },
  },
};
