import { supabase } from "../../lib/supabase/client";

export async function getSections(pageId: string) {
  const { data, error } = await supabase
    .from("sections")
    .select("*")
    .eq("page_id", pageId)
    .order("sort_order");

  if (error) throw error;

  return data ?? [];
}

export async function createDefaultSections(pageId: string) {
  const defaults = [
    {
      type: "hero",
      sort_order: 1,
      config: {
        title: "Premium website generated by AgencyOS",
        subtitle: "Edit this content from the property panel and it will auto-save to Supabase.",
      },
    },
    {
      type: "features",
      sort_order: 2,
      config: {
        items: ["Premium Design", "Fast Performance", "SEO Ready"],
      },
    },
    {
      type: "contact",
      sort_order: 3,
      config: {
        phone: "+91 98765 43210",
        email: "hello@agencyos.ai",
      },
    },
  ];

  const { error } = await supabase.from("sections").insert(defaults.map((section) => ({ page_id: pageId, ...section })));

  if (error) throw error;
}

export async function ensureDefaultSections(pageId: string) {
  const existingSections = await getSections(pageId);

  if (existingSections.length > 0) return existingSections;

  await createDefaultSections(pageId);

  return await getSections(pageId);
}

export async function createSection(pageId: string, type: string, sortOrder: number) {
  const defaultConfig =
    type === "hero"
      ? { title: "New Hero Section", subtitle: "Write a powerful message for this section." }
      : type === "features"
      ? { items: ["Feature One", "Feature Two", "Feature Three"] }
      : type === "gallery"
      ? { eyebrow: "Gallery", title: "Visual gallery", images: ["Image One", "Image Two", "Image Three"] }
      : type === "pricing"
      ? {
          eyebrow: "Pricing",
          title: "Choose your plan",
          subtitle: "Simple packages for every business.",
          plans: [
            { name: "Starter", price: "₹9,999", features: ["Landing page", "WhatsApp CTA", "Mobile responsive"] },
            { name: "Premium", price: "₹24,999", features: ["SEO setup", "Gallery", "Lead form"] },
            { name: "Growth", price: "₹49,999", features: ["Multi-page", "Analytics", "Custom domain"] },
          ],
        }
      : type === "faq"
      ? {
          eyebrow: "FAQ",
          title: "Frequently asked questions",
          items: [
            { question: "How fast can this website go live?", answer: "Most generated websites can be ready within minutes after content is added." },
            { question: "Can I customize the design?", answer: "Yes, AgencyOS is built around editable sections, themes and JSON configuration." },
          ],
        }
      : type === "contact"
      ? { phone: "+91 98765 43210", email: "hello@agencyos.ai" }
      : { title: "New Section", subtitle: "Configure this section from the properties panel." };

  const { data, error } = await supabase
    .from("sections")
    .insert({ page_id: pageId, type, sort_order: sortOrder, config: defaultConfig })
    .select()
    .single();

  if (error) throw error;

  return data;
}
