import { supabase } from "../../lib/supabase/client";

export function getDefaultConfig(type: string) {
  const defaults: Record<string, any> = {
    hero: {
      eyebrow: "Welcome",
      title: "Premium website generated by AgencyOS",
      subtitle: "Edit this content from the property panel and it will auto-save to Supabase.",
      buttonText: "Get Started",
    },
    features: {
      eyebrow: "Services",
      title: "Why choose us",
      subtitle: "Everything your business needs to look premium online.",
      items: ["Premium Design", "Fast Performance", "SEO Ready"],
    },
    gallery: {
      eyebrow: "Gallery",
      title: "Visual gallery",
      images: ["Image One", "Image Two", "Image Three"],
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Choose your plan",
      subtitle: "Simple packages for every business.",
      plans: [
        { name: "Starter", price: "₹9,999", features: ["Landing page", "WhatsApp CTA", "Mobile responsive"] },
        { name: "Premium", price: "₹24,999", features: ["SEO setup", "Gallery", "Lead form"] },
        { name: "Growth", price: "₹49,999", features: ["Multi-page", "Analytics", "Custom domain"] },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Frequently asked questions",
      items: [
        { question: "How fast can this website go live?", answer: "Most generated websites can be ready within minutes." },
        { question: "Can I customize the design?", answer: "Yes, AgencyOS is built around editable sections and themes." },
      ],
    },
    contact: {
      title: "Contact us",
      subtitle: "Reach out and we will help you get started.",
      phone: "+91 98765 43210",
      email: "hello@agencyos.ai",
    },
    testimonials: {
      eyebrow: "Testimonials",
      title: "What our clients say",
      subtitle: "Trusted by businesses across the country.",
      items: [
        { name: "Happy Customer", text: "Amazing service and quality!", role: "Business Owner" },
        { name: "Satisfied Client", text: "Highly recommended.", role: "CEO" },
      ],
    },
    team: {
      eyebrow: "Our Team",
      title: "Meet the people behind our success",
      subtitle: "Passionate experts dedicated to excellence.",
      members: [
        { name: "John Doe", role: "Founder & CEO", bio: "10+ years experience" },
        { name: "Jane Smith", role: "Head of Design", bio: "Award-winning designer" },
      ],
    },
    about: {
      eyebrow: "About Us",
      title: "Our Story",
      description: "We are a passionate team dedicated to delivering excellence in everything we do.",
      mission: "To help businesses grow through premium digital presence.",
      stats: [
        { value: "10+", label: "Years Experience" },
        { value: "500+", label: "Happy Clients" },
        { value: "50+", label: "Team Members" },
      ],
    },
    cta: {
      eyebrow: "Ready?",
      title: "Let's get started today",
      subtitle: "Take the first step towards growing your business online.",
      buttonText: "Get Started",
      secondaryButtonText: "Learn More",
    },
  };

  return defaults[type] ?? { title: "New Section", subtitle: "Configure this section." };
}

export async function getSections(pageId: string) {
  const { data, error } = await supabase
    .from("sections")
    .select("*")
    .eq("page_id", pageId)
    .order("sort_order");

  if (error) throw error;
  return data ?? [];
}

export async function createDefaultSections(pageId: string) {
  const defaults = ["hero", "features", "contact"].map((type, index) => ({
    page_id: pageId,
    type,
    sort_order: index + 1,
    config: getDefaultConfig(type),
  }));

  const { error } = await supabase.from("sections").insert(defaults);
  if (error) throw error;
}

export async function ensureDefaultSections(pageId: string) {
  const existingSections = await getSections(pageId);
  if (existingSections.length > 0) return existingSections;

  await createDefaultSections(pageId);
  return await getSections(pageId);
}

export async function createSection(pageId: string, type: string, sortOrder: number) {
  const { data, error } = await supabase
    .from("sections")
    .insert({
      page_id: pageId,
      type,
      sort_order: sortOrder,
      config: getDefaultConfig(type),
    })
    .select()
    .single();

  if (error) throw error;
  return data;
}
