import { supabase } from "../../lib/supabase/client";

export function getDefaultConfig(type: string) {
  if (type === "hero") {
    return {
      title: "Premium website generated by AgencyOS",
      subtitle: "Edit this content from the property panel and it will auto-save to Supabase.",
      buttonText: "Get Started",
    };
  }

  if (type === "features") {
    return {
      title: "Why choose us",
      subtitle: "Everything your business needs to look premium online.",
      items: ["Premium Design", "Fast Performance", "SEO Ready"],
    };
  }

  if (type === "gallery") {
    return {
      eyebrow: "Gallery",
      title: "Visual gallery",
      images: ["Image One", "Image Two", "Image Three"],
    };
  }

  if (type === "pricing") {
    return {
      eyebrow: "Pricing",
      title: "Choose your plan",
      subtitle: "Simple packages for every business.",
      plans: [
        { name: "Starter", price: "₹9,999", features: ["Landing page", "WhatsApp CTA", "Mobile responsive"] },
        { name: "Premium", price: "₹24,999", features: ["SEO setup", "Gallery", "Lead form"] },
        { name: "Growth", price: "₹49,999", features: ["Multi-page", "Analytics", "Custom domain"] },
      ],
    };
  }

  if (type === "faq") {
    return {
      eyebrow: "FAQ",
      title: "Frequently asked questions",
      items: [
        { question: "How fast can this website go live?", answer: "Most generated websites can be ready within minutes after content is added." },
        { question: "Can I customize the design?", answer: "Yes, AgencyOS is built around editable sections, themes and JSON configuration." },
      ],
    };
  }

  if (type === "contact") {
    return {
      title: "Contact us",
      subtitle: "Reach out and we will help you get started.",
      phone: "+91 98765 43210",
      email: "hello@agencyos.ai",
    };
  }

  return {
    title: "New Section",
    subtitle: "Configure this section from the properties panel.",
  };
}

export async function getSections(pageId: string) {
  const { data, error } = await supabase
    .from("sections")
    .select("*")
    .eq("page_id", pageId)
    .order("sort_order");

  if (error) throw error;
  return data ?? [];
}

export async function createDefaultSections(pageId: string) {
  const defaults = ["hero", "features", "contact"].map((type, index) => ({
    page_id: pageId,
    type,
    sort_order: index + 1,
    config: getDefaultConfig(type),
  }));

  const { error } = await supabase.from("sections").insert(defaults);
  if (error) throw error;
}

export async function ensureDefaultSections(pageId: string) {
  const existingSections = await getSections(pageId);
  if (existingSections.length > 0) return existingSections;

  await createDefaultSections(pageId);
  return await getSections(pageId);
}

export async function createSection(pageId: string, type: string, sortOrder: number) {
  const { data, error } = await supabase
    .from("sections")
    .insert({
      page_id: pageId,
      type,
      sort_order: sortOrder,
      config: getDefaultConfig(type),
    })
    .select()
    .single();

  if (error) throw error;
  return data;
}
