import { supabase } from "../../lib/supabase/client";

const defaultSections = [
  {
    type: "hero",
    sort_order: 1,
    config: {
      title: "Premium website generated by AgencyOS",
      subtitle: "Edit this content from the property panel and it will auto-save to Supabase."
    }
  },
  {
    type: "features",
    sort_order: 2,
    config: {
      items: ["Premium Design", "Fast Performance", "SEO Ready"]
    }
  },
  {
    type: "contact",
    sort_order: 3,
    config: {
      phone: "+91 98765 43210",
      email: "hello@agencyos.ai"
    }
  }
];

export async function initializeProject(projectId: string) {
  const { data: existingHome } = await supabase
    .from("pages")
    .select("*")
    .eq("project_id", projectId)
    .eq("is_home", true)
    .maybeSingle();

  let homePage = existingHome;

  if (!homePage) {
    const { data, error } = await supabase
      .from("pages")
      .insert({
        project_id: projectId,
        title: "Home",
        slug: "/",
        is_home: true,
        sort_order: 0
      })
      .select()
      .single();

    if (error) throw error;
    homePage = data;
  }

  const { data: existingTheme } = await supabase
    .from("themes")
    .select("*")
    .eq("project_id", projectId)
    .maybeSingle();

  if (!existingTheme) {
    const { error } = await supabase.from("themes").insert({
      project_id: projectId,
      primary_color: "#06b6d4",
      secondary_color: "#8b5cf6",
      font: "Inter",
      radius: "xl",
      mode: "dark"
    });

    if (error) throw error;
  }

  const { data: existingSections } = await supabase
    .from("sections")
    .select("id")
    .eq("page_id", homePage.id);

  if (!existingSections || existingSections.length === 0) {
    const { error } = await supabase.from("sections").insert(
      defaultSections.map((section) => ({
        page_id: homePage.id,
        ...section
      }))
    );

    if (error) throw error;
  }
}
