import { supabase } from "../../lib/supabase/client";
import type { Project } from "../../types/project";

export async function getCurrentUserId() {
  const { data, error } = await supabase.auth.getUser();

  if (error) throw error;
  if (!data.user) throw new Error("User not logged in");

  return data.user.id;
}

export async function fetchProjects() {
  const { data, error } = await supabase
    .from("projects")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) throw error;

  return data as Project[];
}

export async function createProject(input: {
  name: string;
  industry: string;
  template: string;
}) {
  const owner = await getCurrentUserId();

  const slug =
    input.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") +
    "-" +
    Date.now();

  const { data, error } = await supabase
    .from("projects")
    .insert({
      owner,
      name: input.name,
      industry: input.industry,
      template: input.template,
      slug,
      description: `${input.industry} website generated by AgencyOS`,
      published: false,
    })
    .select()
    .single();

  if (error) throw error;

  const project = data as Project;

const { initializeProject } = await import("./initializeProject");
await initializeProject(project.id);

return project;
}

export async function deleteProject(id: string) {
  const { error } = await supabase.from("projects").delete().eq("id", id);

  if (error) throw error;
}

