/**
 * HTML/CSS Exporter
 *
 * Generates a single static HTML file with embedded CSS.
 * Fully responsive, production-ready, no JS dependencies.
 */

import type { SectionConfig } from '../../engine/types';
import type { DesignTokens } from '../../themes/tokens';
import type { ExportResult } from '../types';
import { generateCSS } from '../utils/cssGenerator';
import { generateSectionHTML } from '../utils/htmlGenerator';

export function exportAsHTML(
  sections: SectionConfig[],
  tokens: DesignTokens,
  projectName: string,
): ExportResult {
  const css = generateCSS(tokens);
  const sectionsHTML = sections.map((s) => generateSectionHTML(s)).join('\n\n');

  const layoutCSS = generateLayoutCSS();

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName}</title>
  <meta name="description" content="${projectName} - Generated by AgencyOS AI Website Builder" />
  
  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@400;600;700&family=DM+Sans:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700;800&family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
  
  <style>
${css}

${layoutCSS}
  </style>
</head>
<body>
${sectionsHTML}
</body>
</html>`;

  const files = [{ path: 'index.html', content: html, language: 'html' }];
  const totalSize = files.reduce((sum, f) => sum + f.content.length, 0);

  return { format: 'html', files, totalSize };
}

function generateLayoutCSS(): string {
  return `/* Layout Styles */
.navbar {
  position: sticky;
  top: 0;
  z-index: 100;
  background: var(--color-background);
  border-bottom: 1px solid var(--color-border);
  padding: 1rem var(--section-x);
}
.navbar-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.navbar-brand {
  font-family: var(--font-heading);
  font-size: 1.25rem;
  font-weight: var(--font-heading-weight);
  color: var(--color-text);
}
.navbar-links {
  display: flex;
  gap: 2rem;
}
.nav-link {
  font-size: 0.875rem;
  color: var(--color-text-muted);
  font-weight: 500;
  transition: color 0.2s;
}
.nav-link:hover { color: var(--color-text); }

/* Hero */
.hero {
  padding: var(--section-y) var(--section-x);
  position: relative;
  overflow: hidden;
}
.hero-inner {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3rem;
  align-items: center;
}
.hero--centered .hero-inner { grid-template-columns: 1fr; text-align: center; }
.hero-content--centered { max-width: 800px; margin-inline: auto; }
.hero h1 { color: var(--color-text); margin-bottom: 1.25rem; }
.hero-subtitle { color: var(--color-text-muted); font-size: 1.125rem; max-width: 600px; }
.hero--centered .hero-subtitle { margin-inline: auto; }
.hero-actions { display: flex; gap: 1rem; margin-top: 2rem; flex-wrap: wrap; }
.hero--centered .hero-actions { justify-content: center; }
.hero-image img { border-radius: var(--image-radius); border: 1px solid var(--color-border); }
.eyebrow { display: inline-block; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; color: var(--color-primary); margin-bottom: 0.75rem; }

/* Section header */
.section-header { text-align: center; max-width: 640px; margin: 0 auto 3rem; }
.section-header h2 { color: var(--color-text); }
.section-header p { color: var(--color-text-muted); margin-top: 1rem; }

/* Features */
.features-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: var(--gap-lg); }
.feature-card h3 { font-size: var(--font-h4); color: var(--color-text); margin-bottom: 0.5rem; }
.feature-card p { font-size: 0.875rem; color: var(--color-text-muted); }

/* About */
.about-inner { display: grid; grid-template-columns: 1fr 1fr; gap: 3rem; align-items: center; }
.about-image img { border-radius: var(--image-radius); }
.mission { margin-top: 1.5rem; padding: 1rem 1.5rem; border-left: 3px solid var(--color-primary); color: var(--color-text-muted); font-style: italic; }

/* Gallery */
.gallery-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1rem; }
.gallery-item img { border-radius: var(--card-radius); width: 100%; height: 200px; object-fit: cover; }

/* Testimonials */
.testimonials-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: var(--gap-lg); }
.testimonial-card .stars { color: var(--color-primary); margin-bottom: 1rem; }
.testimonial-card blockquote { color: var(--color-text-muted); font-style: italic; margin-bottom: 1.5rem; line-height: var(--line-height); }
.testimonial-card cite { display: block; font-style: normal; }
.testimonial-card cite strong { color: var(--color-text); display: block; }
.testimonial-card cite span { font-size: 0.75rem; color: var(--color-text-subtle); }

/* Pricing */
.pricing-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: var(--gap-lg); }
.pricing-card { display: flex; flex-direction: column; position: relative; padding: var(--card-padding-lg); }
.pricing-card--popular { border: 2px solid var(--color-primary); }
.pricing-card .badge { position: absolute; top: -12px; left: 50%; transform: translateX(-50%); background: var(--btn-primary-bg); color: var(--btn-primary-text); padding: 0.25rem 1rem; border-radius: var(--radius-full); font-size: 0.75rem; font-weight: 600; }
.pricing-card h3 { font-size: 1.25rem; margin-bottom: 0.5rem; }
.pricing-card .price { font-size: var(--font-h2); font-weight: var(--font-heading-weight); color: var(--color-text); margin-bottom: 1.5rem; }
.features-list { list-style: none; flex: 1; margin-bottom: 2rem; }
.features-list li { display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem 0; font-size: 0.875rem; color: var(--color-text-muted); }
.features-list .check { color: var(--color-primary); }

/* FAQ */
.faq-list { max-width: 720px; margin-inline: auto; }
.faq-item { border: 1px solid var(--color-border); border-radius: var(--card-radius); margin-bottom: 0.75rem; overflow: hidden; background: var(--color-surface); }
.faq-item summary { padding: 1.25rem; cursor: pointer; font-weight: 600; color: var(--color-text); list-style: none; }
.faq-item summary::-webkit-details-marker { display: none; }
.faq-item p { padding: 0 1.25rem 1.25rem; color: var(--color-text-muted); }

/* Contact */
.contact-inner { display: grid; grid-template-columns: 1fr 1fr; gap: 3rem; }
.contact-form form { display: flex; flex-direction: column; gap: 1rem; margin-top: 1.5rem; }
.form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
.contact-form input, .contact-form textarea { width: 100%; padding: 0.875rem 1rem; background: var(--color-surface); border: 1px solid var(--color-border); border-radius: var(--input-radius); color: var(--color-text); font-family: var(--font-body); font-size: 0.875rem; }
.contact-info { display: flex; flex-direction: column; justify-content: center; gap: 1rem; padding: 2rem; background: var(--color-surface); border: 1px solid var(--color-border); border-radius: var(--card-radius); }
.contact-info p { color: var(--color-text-muted); font-size: 0.875rem; }

/* CTA */
.cta-section { padding: var(--section-y) var(--section-x); background: linear-gradient(var(--color-gradient-angle), var(--color-gradient-from), var(--color-gradient-to)); text-align: center; }
.cta-inner h2 { color: var(--btn-primary-text); }
.cta-inner p { color: var(--btn-primary-text); opacity: 0.85; margin: 1rem auto; max-width: 600px; }
.cta-actions { display: flex; gap: 1rem; justify-content: center; margin-top: 2rem; }

/* Stats */
.stats-section { padding: var(--section-y) var(--section-x); background: var(--color-surface); border-top: 1px solid var(--color-border); border-bottom: 1px solid var(--color-border); }
.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 2rem; text-align: center; }
.stat-value { font-family: var(--font-heading); font-size: var(--font-h2); font-weight: var(--font-heading-weight); color: var(--color-primary); }
.stat-label { font-size: 0.875rem; color: var(--color-text-muted); margin-top: 0.25rem; }

/* Footer */
.footer { padding: var(--section-y) var(--section-x); background: var(--color-surface); border-top: 1px solid var(--color-border); }
.footer-inner { display: grid; grid-template-columns: 2fr 1fr 1fr; gap: 3rem; }
.footer-brand h3 { font-size: 1.25rem; margin-bottom: 0.5rem; }
.footer-brand p { font-size: 0.875rem; color: var(--color-text-muted); }
.footer-links ul { list-style: none; }
.footer-links li { margin-bottom: 0.5rem; }
.footer-links a { font-size: 0.875rem; color: var(--color-text-muted); transition: color 0.2s; }
.footer-links a:hover { color: var(--color-text); }
.footer-contact p { font-size: 0.875rem; color: var(--color-text-muted); margin-bottom: 0.25rem; }
.footer-bottom { margin-top: 2rem; padding-top: 1.5rem; border-top: 1px solid var(--color-border); text-align: center; }
.footer-bottom p { font-size: 0.75rem; color: var(--color-text-subtle); }

/* Responsive */
@media (max-width: 768px) {
  .hero-inner, .about-inner, .contact-inner { grid-template-columns: 1fr; }
  .footer-inner { grid-template-columns: 1fr; gap: 2rem; }
  .navbar-links { display: none; }
  .form-row { grid-template-columns: 1fr; }
  h1 { font-size: clamp(2rem, 5vw, var(--font-h1)); }
  h2 { font-size: clamp(1.5rem, 4vw, var(--font-h2)); }
}`;
}
