/**
 * CSS Generator Utility
 *
 * Converts DesignTokens into production-ready CSS custom properties
 * and utility classes. Used by all export formats.
 */

import type { DesignTokens } from '../../themes/tokens';

/**
 * Generate a complete CSS file from design tokens.
 * Includes custom properties and base styles.
 */
export function generateCSS(tokens: DesignTokens): string {
  return `/* Generated by AgencyOS AI Website Builder */
/* Design Tokens as CSS Custom Properties */

:root {
  /* Colors */
  --color-primary: ${tokens.colors.primary};
  --color-primary-light: ${tokens.colors.primaryLight};
  --color-primary-dark: ${tokens.colors.primaryDark};
  --color-secondary: ${tokens.colors.secondary};
  --color-accent: ${tokens.colors.accent};
  --color-background: ${tokens.colors.background};
  --color-surface: ${tokens.colors.surface};
  --color-surface-hover: ${tokens.colors.surfaceHover};
  --color-text: ${tokens.colors.text};
  --color-text-muted: ${tokens.colors.textMuted};
  --color-text-subtle: ${tokens.colors.textSubtle};
  --color-border: ${tokens.colors.border};
  --color-border-hover: ${tokens.colors.borderHover};
  --color-gradient-from: ${tokens.colors.gradient.from};
  --color-gradient-to: ${tokens.colors.gradient.to};
  --color-gradient-angle: ${tokens.colors.gradient.angle}deg;

  /* Typography */
  --font-heading: ${tokens.typography.headingFont};
  --font-body: ${tokens.typography.bodyFont};
  --font-heading-weight: ${tokens.typography.headingWeight};
  --font-body-weight: ${tokens.typography.bodyWeight};
  --font-h1: ${tokens.typography.h1};
  --font-h2: ${tokens.typography.h2};
  --font-h3: ${tokens.typography.h3};
  --font-h4: ${tokens.typography.h4};
  --font-body-size: ${tokens.typography.body};
  --font-small: ${tokens.typography.small};
  --line-height: ${tokens.typography.lineHeight};
  --heading-line-height: ${tokens.typography.headingLineHeight};
  --letter-spacing: ${tokens.typography.letterSpacing};
  --heading-letter-spacing: ${tokens.typography.headingLetterSpacing};

  /* Spacing */
  --section-y: ${tokens.spacing.sectionY};
  --section-x: ${tokens.spacing.sectionX};
  --container-max: ${tokens.spacing.containerMax};
  --gap: ${tokens.spacing.gap};
  --gap-lg: ${tokens.spacing.gapLg};
  --card-padding: ${tokens.spacing.cardPadding};
  --card-padding-lg: ${tokens.spacing.cardPaddingLg};

  /* Shapes */
  --radius: ${tokens.shapes.radius};
  --radius-sm: ${tokens.shapes.radiusSm};
  --radius-lg: ${tokens.shapes.radiusLg};
  --radius-xl: ${tokens.shapes.radiusXl};
  --radius-full: ${tokens.shapes.radiusFull};
  --card-radius: ${tokens.shapes.cardRadius};
  --button-radius: ${tokens.shapes.buttonRadius};
  --image-radius: ${tokens.shapes.imageRadius};
  --input-radius: ${tokens.shapes.inputRadius};

  /* Effects */
  --shadow: ${tokens.effects.shadow};
  --shadow-lg: ${tokens.effects.shadowLg};
  --card-shadow: ${tokens.effects.cardShadow};
  --button-shadow: ${tokens.effects.buttonShadow};
  --glow-color: ${tokens.effects.glowColor};
  --glow-opacity: ${tokens.effects.glowOpacity};

  /* Buttons */
  --btn-primary-bg: ${tokens.buttons.primary.bg};
  --btn-primary-text: ${tokens.buttons.primary.text};
  --btn-primary-hover: ${tokens.buttons.primary.hoverBg};
  --btn-primary-shadow: ${tokens.buttons.primary.shadow};
  --btn-primary-padding: ${tokens.buttons.primary.padding};
  --btn-primary-font-size: ${tokens.buttons.primary.fontSize};
  --btn-primary-font-weight: ${tokens.buttons.primary.fontWeight};
  --btn-secondary-bg: ${tokens.buttons.secondary.bg};
  --btn-secondary-text: ${tokens.buttons.secondary.text};
  --btn-secondary-border: ${tokens.buttons.secondary.border};
  --btn-secondary-hover: ${tokens.buttons.secondary.hoverBg};
  --btn-secondary-padding: ${tokens.buttons.secondary.padding};
  --btn-secondary-font-size: ${tokens.buttons.secondary.fontSize};
  --btn-secondary-font-weight: ${tokens.buttons.secondary.fontWeight};
}

/* Base Styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  font-family: var(--font-body);
  font-weight: var(--font-body-weight);
  font-size: var(--font-body-size);
  line-height: var(--line-height);
  color: var(--color-text);
  background-color: var(--color-background);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  font-weight: var(--font-heading-weight);
  line-height: var(--heading-line-height);
  letter-spacing: var(--heading-letter-spacing);
}

h1 { font-size: var(--font-h1); }
h2 { font-size: var(--font-h2); }
h3 { font-size: var(--font-h3); }
h4 { font-size: var(--font-h4); }

img {
  max-width: 100%;
  height: auto;
  display: block;
}

a {
  color: inherit;
  text-decoration: none;
}

/* Utility Classes */
.container {
  max-width: var(--container-max);
  margin-inline: auto;
  padding-inline: var(--section-x);
}

.section {
  padding-block: var(--section-y);
  padding-inline: var(--section-x);
}

.btn-primary {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: var(--btn-primary-bg);
  color: var(--btn-primary-text);
  padding: var(--btn-primary-padding);
  border-radius: var(--button-radius);
  font-size: var(--btn-primary-font-size);
  font-weight: var(--btn-primary-font-weight);
  font-family: var(--font-body);
  border: none;
  cursor: pointer;
  transition: transform 0.2s, opacity 0.2s;
  box-shadow: var(--btn-primary-shadow);
}

.btn-primary:hover {
  transform: scale(1.02);
}

.btn-secondary {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: var(--btn-secondary-bg);
  color: var(--btn-secondary-text);
  border: var(--btn-secondary-border);
  padding: var(--btn-secondary-padding);
  border-radius: var(--button-radius);
  font-size: var(--btn-secondary-font-size);
  font-weight: var(--btn-secondary-font-weight);
  font-family: var(--font-body);
  cursor: pointer;
  transition: background 0.2s;
}

.btn-secondary:hover {
  background: var(--btn-secondary-hover);
}

.card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--card-radius);
  padding: var(--card-padding);
  box-shadow: var(--card-shadow);
}
`;
}
