import { supabase } from "../../lib/supabase/client";
import type { OnboardingData } from "../../types/onboarding";
import type { Project } from "../../types/project";
import { getIndustryTemplate } from "./industryTemplates";

/**
 * AI Website Generation Service
 *
 * Generates a complete website from onboarding data.
 * Uses industry-specific templates enhanced with user-provided business info.
 *
 * In production, this would call an LLM API (OpenAI/Anthropic).
 * For now, it uses intelligent template generation with the user's data.
 */

export async function generateAndCreateProject(data: OnboardingData): Promise<Project> {
  const owner = await getCurrentUserId();
  const slug = generateSlug(data.businessName);

  // 1. Create project record
  const { data: project, error: projectError } = await supabase
    .from("projects")
    .insert({
      owner,
      name: data.businessName,
      industry: data.industry,
      template: data.industry,
      slug,
      description: data.businessDescription || `${data.industry} website generated by AgencyOS`,
      primary_color: data.primaryColor,
      secondary_color: data.secondaryColor,
      logo: data.logo || null,
      published: false,
    })
    .select()
    .single();

  if (projectError) throw projectError;

  // 2. Create home page
  const { data: homePage, error: pageError } = await supabase
    .from("pages")
    .insert({
      project_id: project.id,
      title: "Home",
      slug: "/",
      is_home: true,
      sort_order: 0,
    })
    .select()
    .single();

  if (pageError) throw pageError;

  // 3. Create additional pages
  const additionalPages = [
    { title: "About", slug: "/about", sort_order: 1 },
    { title: "Services", slug: "/services", sort_order: 2 },
    { title: "Contact", slug: "/contact", sort_order: 3 },
  ];

  await supabase.from("pages").insert(
    additionalPages.map((p) => ({ ...p, project_id: project.id, is_home: false }))
  );

  // 4. Generate sections from AI template
  const sections = generateSections(data);
  const sectionRecords = sections.map((section, index) => ({
    page_id: homePage.id,
    type: section.type,
    sort_order: index + 1,
    config: section.config,
  }));

  const { error: sectionsError } = await supabase.from("sections").insert(sectionRecords);
  if (sectionsError) throw sectionsError;

  // 5. Create theme
  const { error: themeError } = await supabase.from("themes").insert({
    project_id: project.id,
    primary_color: data.primaryColor,
    secondary_color: data.secondaryColor,
    font: "Inter",
    radius: "xl",
    mode: "dark",
  });

  if (themeError) throw themeError;

  return project as Project;
}

function generateSections(data: OnboardingData) {
  const template = getIndustryTemplate(data.industry);
  const businessName = data.businessName || "Your Business";
  const tagline = data.tagline || template.defaultTagline;
  const description = data.businessDescription || template.defaultDescription;
  const services = data.services.length > 0 ? data.services : template.defaultServices;
  const phone = data.phone || "+91 98765 43210";
  const email = data.email || "hello@yourbusiness.com";
  const whatsapp = data.whatsapp || data.phone || "";

  return [
    {
      type: "hero",
      config: {
        eyebrow: template.heroEyebrow,
        title: `${businessName} — ${tagline}`,
        subtitle: description || `Welcome to ${businessName}. ${template.defaultDescription}`,
        buttonText: template.heroCta,
        buttonLink: "#contact",
        backgroundGradient: `linear-gradient(135deg, ${data.primaryColor}22, ${data.secondaryColor}22)`,
      },
    },
    {
      type: "features",
      config: {
        eyebrow: "Our Services",
        title: `What we offer at ${businessName}`,
        subtitle: `Discover our range of ${data.industry} services designed for you.`,
        items: services,
      },
    },
    {
      type: "gallery",
      config: {
        eyebrow: "Gallery",
        title: `Experience ${businessName}`,
        images: template.defaultGallery,
      },
    },
    {
      type: "pricing",
      config: {
        eyebrow: "Pricing",
        title: template.pricingTitle || "Our Packages",
        subtitle: "Choose the perfect plan for your needs.",
        plans: template.defaultPlans,
      },
    },
    {
      type: "faq",
      config: {
        eyebrow: "FAQ",
        title: "Frequently Asked Questions",
        items: template.defaultFAQ,
      },
    },
    {
      type: "contact",
      config: {
        title: "Get in Touch",
        subtitle: `Reach out to ${businessName}. We'd love to hear from you.`,
        phone,
        email,
        whatsapp,
        address: [data.address, data.city, data.state].filter(Boolean).join(", "),
        openingHours: data.openingHours,
        instagram: data.instagram,
        facebook: data.facebook,
        linkedin: data.linkedin,
        googleBusiness: data.googleBusiness,
      },
    },
  ];
}

function generateSlug(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") +
    "-" +
    Date.now()
  );
}

async function getCurrentUserId(): Promise<string> {
  const { data, error } = await supabase.auth.getUser();
  if (error) throw error;
  if (!data.user) throw new Error("User not logged in");
  return data.user.id;
}
